---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: echo-server
  name: echo-server
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: echo-server-env
  namespace: echo-server
data:
    LOGS__FORMAT: "object"
    LOGS__SEQ__ENABLED: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  labels:
    app: echo-server
  namespace: echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      name: echo-server
      labels:
        app: echo-server
    spec:
      containers:
        - name: echo-server
          image: ealen/echo-server:0.9.2
          ports:
            - containerPort: 80
              name: http
          envFrom:
            - configMapRef:
                name: echo-server-env
---
kind: Service
apiVersion: v1
metadata:
  name: echo-server-svc
  namespace: echo-server
spec:
  selector:
    app: echo-server
  ports:
    - name: echo-server-svc
      port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-server-ingress
  namespace: echo-server
  labels:
    app: echo-server
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: echo-server-svc
      port:
        name: echo-server-svc
  rules:
    - host: echo-server.dev.astria.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echo-server-svc
                port:
                  name: echo-server-svc
