---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: echo
  name: echo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: echo-env
  namespace: echo
data:
    LOGS__FORMAT: "object"
    LOGS__SEQ__ENABLED: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  labels:
    app: echo
  namespace: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      name: echo-sercver
      labels:
        app: echo
    spec:
      containers:
        - name: echo
          image: ealen/echo-server:latest
          ports:
            - containerPort: 80
              name: echo-http
          envFrom:
            - configMapRef:
                name: echo-env
---
kind: Service
apiVersion: v1
metadata:
  name: echo-svc
  namespace: echo
spec:
  selector:
    app: echo
  ports:
    - name: echo-svc
      port: 80
      targetPort: echo-http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-ingress
  namespace: echo
  labels:
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: echo-svc
      port:
        name: echo-svc
  rules:
    - host: echo.dev.astria.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echo-svc
                port:
                  name: echo-svc
