apiVersion: v1
kind: Service
metadata:
  name: {{ include "echo-server.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "echo-server.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "echo-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
